### ISSUE TITLE
❗No social picture preview in some website

### ISSUE THREAD

**Issue by karinzaa** [TNI-Cybersec/tni-cybersec.github.io#3]
❗No social picture preview in some website
![image](https://user-images.githubusercontent.com/25452435/166115489-445fefb4-8ea0-4d22-97ec-95b8e12b9f82.png)
![image](https://user-images.githubusercontent.com/25452435/166115518-9f60d7b0-2fda-4d89-a8f2-6a81ced2d540.png)

**Comment by richeyphu** [comment]
🛠 Fixed
<img width="527" alt="Screen Shot 2022-05-13 at 16 05 29" src="https://user-images.githubusercontent.com/55230837/168250527-5e083d5c-ce5d-4fea-91cd-8823e1b2a4e1.png">
